{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.progames723",
    "module": "hmmm-forge",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-forge-0.5.jar",
          "url": "hmmm-forge-0.5.jar",
          "size": 207598,
          "sha512": "defcf0f4b80acd6bea6d15f3fee3463b499c0a5e6f14045125ffaca7960bb55c7aad2dfa0dd83bb7ad52a9f3ae9cd6a10657f4b81a7135497b2ec0a635ce25d4",
          "sha256": "30a703146d5dd481bdd66607bbf9dfc3af7d6734a32642f97da4c2de6cb82b90",
          "sha1": "e70063d1eadfaae2374a3a8c493a9ade7fea3078",
          "md5": "fa8f41030d41733c02ee837b43fcd3ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.3.6"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-forge-0.5.jar",
          "url": "hmmm-forge-0.5.jar",
          "size": 207598,
          "sha512": "defcf0f4b80acd6bea6d15f3fee3463b499c0a5e6f14045125ffaca7960bb55c7aad2dfa0dd83bb7ad52a9f3ae9cd6a10657f4b81a7135497b2ec0a635ce25d4",
          "sha256": "30a703146d5dd481bdd66607bbf9dfc3af7d6734a32642f97da4c2de6cb82b90",
          "sha1": "e70063d1eadfaae2374a3a8c493a9ade7fea3078",
          "md5": "fa8f41030d41733c02ee837b43fcd3ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hmmm-forge-0.5-sources.jar",
          "url": "hmmm-forge-0.5-sources.jar",
          "size": 28317,
          "sha512": "d7010208a7148219330d79aa395568824f3f2f6ce3916c5e502d8463e82951ebd399dae9b6b79ab7cbd1f4a3bdcba7f03d6c9567a28e91bcfc36d82b91324a31",
          "sha256": "4ca4591f65b26a05f96387cb2cd2491f80c47c4c062ef1b6d2837c84c87a90ff",
          "sha1": "baab04385102fe58f2382c466afe87465bfb98f0",
          "md5": "5ad85ac016daa5ae5341edcbab691897"
        }
      ]
    }
  ]
}
