{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.progames723",
    "module": "hmmm-forge",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-forge-0.5.jar",
          "url": "hmmm-forge-0.5.jar",
          "size": 207770,
          "sha512": "84d80f329a954210d6cffb539dd5de6a1ddaf79a29e2d8281d9a612b63ebf23095346b0e78c3733a2ec4eb5acc1e263d64e41fd7595cc0a4510e448e9d824a25",
          "sha256": "9fee68c2aedcf6b4fc3560ec1abfdcc1657a4e02c281304e664b1d6a4e464372",
          "sha1": "d60a4ca90b49826a07d0a062cfc84d8676e5aa6d",
          "md5": "826e004c3101a42190c084e673c91765"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.3.6"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-forge-0.5.jar",
          "url": "hmmm-forge-0.5.jar",
          "size": 207770,
          "sha512": "84d80f329a954210d6cffb539dd5de6a1ddaf79a29e2d8281d9a612b63ebf23095346b0e78c3733a2ec4eb5acc1e263d64e41fd7595cc0a4510e448e9d824a25",
          "sha256": "9fee68c2aedcf6b4fc3560ec1abfdcc1657a4e02c281304e664b1d6a4e464372",
          "sha1": "d60a4ca90b49826a07d0a062cfc84d8676e5aa6d",
          "md5": "826e004c3101a42190c084e673c91765"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hmmm-forge-0.5-sources.jar",
          "url": "hmmm-forge-0.5-sources.jar",
          "size": 28572,
          "sha512": "73c751999d19b786ba93f369580a2b6d1ef6693804ca405b3cc1e043e7c397747f0723e8ba019feb4b5fd0fa737cdfed93864e516517142b6983dbd2d7f0f7ce",
          "sha256": "a6de07da5e975d01e49e2a28fdfc1ba6dd0e255ad3056272b3e3bcf046b3a938",
          "sha1": "5e72ee1bba9ecd2cc0100e0280c95e2bf85118a6",
          "md5": "2a0376f244e11357652721793e9dcd43"
        }
      ]
    }
  ]
}
