{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.progames723",
    "module": "hmmm-common",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-common-0.5.jar",
          "url": "hmmm-common-0.5.jar",
          "size": 46689,
          "sha512": "ff1e33ed80348802676bf10c863d687ba65f66e2bac07a07396baf4513760eb1ef66995f71a96ee388dc553b3afffe80da77324a38e96e4104cc6c10e629431f",
          "sha256": "b3d8bc24b280c3c81c26fe43476f79d99cabe6505b30dcd2c49602af4e52da3c",
          "sha1": "b41bab0c957f4dc8cf5473260ce811506e722004",
          "md5": "b18972bea0a716ee37998121b2314b81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.3.4"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "10.0.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.6"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-common-0.5.jar",
          "url": "hmmm-common-0.5.jar",
          "size": 46689,
          "sha512": "ff1e33ed80348802676bf10c863d687ba65f66e2bac07a07396baf4513760eb1ef66995f71a96ee388dc553b3afffe80da77324a38e96e4104cc6c10e629431f",
          "sha256": "b3d8bc24b280c3c81c26fe43476f79d99cabe6505b30dcd2c49602af4e52da3c",
          "sha1": "b41bab0c957f4dc8cf5473260ce811506e722004",
          "md5": "b18972bea0a716ee37998121b2314b81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hmmm-common-0.5-sources.jar",
          "url": "hmmm-common-0.5-sources.jar",
          "size": 25092,
          "sha512": "15dc90b4c960c9c487c89d9aaa5736621dc0f53ff62c8b2d66a0c43f82f1e724a24fa1ac06253133a440e05e60492805e453981e177f4f2a94d18157d189225a",
          "sha256": "c1e05532e2c7b0720dd72cda386fb3a056312b73dced63ea1391c8e56abd65ca",
          "sha1": "7bab50108af478e5feaa600f2277bfc09d60e9e0",
          "md5": "ce030fc4f0805ce27839037c294f8654"
        }
      ]
    }
  ]
}
