{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.progames723",
    "module": "hmmm-fabric",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-fabric-0.5.jar",
          "url": "hmmm-fabric-0.5.jar",
          "size": 202758,
          "sha512": "cfbf7d82070223a3963818d54af8d9978112e2ab63dd81e0519d730348c3164c915e778a4f002f353c46f46402cd21ebac13f63b848d49cbf3c5b3ada1420b8c",
          "sha256": "1779b7a683fc4e78800361b750558d2a5b6ec591af10ac24ad23fd8c57ac499e",
          "sha1": "cef715117fec68771d17c16d8fde9991d9b616eb",
          "md5": "77825efabbfc9dbfba994f8b001ad386"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.3.4"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "10.0.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-fabric-0.5.jar",
          "url": "hmmm-fabric-0.5.jar",
          "size": 202758,
          "sha512": "cfbf7d82070223a3963818d54af8d9978112e2ab63dd81e0519d730348c3164c915e778a4f002f353c46f46402cd21ebac13f63b848d49cbf3c5b3ada1420b8c",
          "sha256": "1779b7a683fc4e78800361b750558d2a5b6ec591af10ac24ad23fd8c57ac499e",
          "sha1": "cef715117fec68771d17c16d8fde9991d9b616eb",
          "md5": "77825efabbfc9dbfba994f8b001ad386"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hmmm-fabric-0.5-sources.jar",
          "url": "hmmm-fabric-0.5-sources.jar",
          "size": 26568,
          "sha512": "e838015fe845b329bfa852458da0491bb14770d8a37c91cfa5a0cabfef938ecee6b507bc2d63d7374b54faa6088c76a1c07ad93a8f920c750bf46a8176df43a0",
          "sha256": "1a7d6a0597578af43b918d8ee1c92f52ee14cf1aa973bda480b34b13d3707aba",
          "sha1": "b7db960c479dcbdb5206c86fc44140002e0748e6",
          "md5": "1ab2691ebef340302cbdf4e70103d371"
        }
      ]
    }
  ]
}
