{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.progames723",
    "module": "hmmm-fabric",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-fabric-0.2.jar",
          "url": "hmmm-fabric-0.2.jar",
          "size": 17092,
          "sha512": "9f2d9381a71f687ccb1af78b1c1a6504fdbf6e20383ae9824425d7e7cf45dde4c5aefcc9c03217cfc4edd4e715927296a7ab65af262b35e2d6c4ffa875b6290c",
          "sha256": "b820a043c990f7d5c4bb21538736e2f29bca4284e7fa02eca6de867fc8784fa4",
          "sha1": "ec368b3996f66b26656d34021a14f86cd1fe93da",
          "md5": "079cffd565375a2214979d91b82d7d10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-fabric",
          "version": {
            "requires": "0.3.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.3+1.20.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "10.0.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-fabric-0.2.jar",
          "url": "hmmm-fabric-0.2.jar",
          "size": 17092,
          "sha512": "9f2d9381a71f687ccb1af78b1c1a6504fdbf6e20383ae9824425d7e7cf45dde4c5aefcc9c03217cfc4edd4e715927296a7ab65af262b35e2d6c4ffa875b6290c",
          "sha256": "b820a043c990f7d5c4bb21538736e2f29bca4284e7fa02eca6de867fc8784fa4",
          "sha1": "ec368b3996f66b26656d34021a14f86cd1fe93da",
          "md5": "079cffd565375a2214979d91b82d7d10"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hmmm-fabric-0.2-sources.jar",
          "url": "hmmm-fabric-0.2-sources.jar",
          "size": 13417,
          "sha512": "30fcdcd0cf1f95d334465b33b92baf3b5de00520c9287e4bc2f70b2943ef9f03931401f16782027d46225375aeea493899c58428da076c4631213ae15170e6aa",
          "sha256": "a19ce5e0238a750e455b902da6eeac745363ee1d7b41369232431caf943bf815",
          "sha1": "7fab6446337c5150194ea26c4e652bd2b770f57a",
          "md5": "94c1f864070fc62d4b55c6b5fa30c517"
        }
      ]
    }
  ]
}
