{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.progames723",
    "module": "hmmm-neoforge",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hmmm-neoforge-0.5.jar",
          "url": "hmmm-neoforge-0.5.jar",
          "size": 203494,
          "sha512": "c0ec7252f5d4e4e29158b4548416033e33a84283d3463b29deafc20bbc6682e87edebe3f8ba0d8e90fb117a2730cfad0690a9933b9eb9a50e5419255cd4db8d6",
          "sha256": "2a257b534977f3de779c7e06ea0990ab892e6483de19ff018004d11e31dccd8e",
          "sha1": "a8957af31cc2808af82f81776a7cec2cdd02c60b",
          "md5": "0070fbfdaa967efe402c5a89fd3efaa7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.3.6"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-neoforge-0.5.jar",
          "url": "hmmm-neoforge-0.5.jar",
          "size": 203494,
          "sha512": "c0ec7252f5d4e4e29158b4548416033e33a84283d3463b29deafc20bbc6682e87edebe3f8ba0d8e90fb117a2730cfad0690a9933b9eb9a50e5419255cd4db8d6",
          "sha256": "2a257b534977f3de779c7e06ea0990ab892e6483de19ff018004d11e31dccd8e",
          "sha1": "a8957af31cc2808af82f81776a7cec2cdd02c60b",
          "md5": "0070fbfdaa967efe402c5a89fd3efaa7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hmmm-neoforge-0.5-sources.jar",
          "url": "hmmm-neoforge-0.5-sources.jar",
          "size": 27156,
          "sha512": "685bcab354a46a6a48cae87b8058712c68c56b5c4b1b091b810387627d41b6ed8591db3e11604dd072a71c16cadc17b8489455bf0e9d52d10e9fef8da95a9f45",
          "sha256": "c7034786807fb1db485784b5d77c28104949dd168499287f439d6456ac258762",
          "sha1": "76d3c63520cf2cd312efe33abb9c2b5504333c3b",
          "md5": "9042da53d9208a4bee9ac163faa263cc"
        }
      ]
    }
  ]
}
