{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.progames723",
    "module": "hmmm-neoforge",
    "version": "0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hmmm-neoforge-0.5.jar",
          "url": "hmmm-neoforge-0.5.jar",
          "size": 203669,
          "sha512": "0f535273f46ec40adf2f9cfb388c1b07463967f9961bed9b7c50d20fb1efa3b76e7bb63a95413cbce42569e5e968f1d4f1033fe0d746aed554e6b33a46981d71",
          "sha256": "7f8f9dcdfe3c672bc759f30e409f3c608008ff545a1ea38116dba49bdab50189",
          "sha1": "ea7af90ef48e0ee878c2d6b3edf7d9b38ccb9769",
          "md5": "9c4c371bd566f6b846501e80e5d8d03c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-neoforge",
          "version": {
            "requires": "0.3.6"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "10.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "hmmm-neoforge-0.5.jar",
          "url": "hmmm-neoforge-0.5.jar",
          "size": 203669,
          "sha512": "0f535273f46ec40adf2f9cfb388c1b07463967f9961bed9b7c50d20fb1efa3b76e7bb63a95413cbce42569e5e968f1d4f1033fe0d746aed554e6b33a46981d71",
          "sha256": "7f8f9dcdfe3c672bc759f30e409f3c608008ff545a1ea38116dba49bdab50189",
          "sha1": "ea7af90ef48e0ee878c2d6b3edf7d9b38ccb9769",
          "md5": "9c4c371bd566f6b846501e80e5d8d03c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hmmm-neoforge-0.5-sources.jar",
          "url": "hmmm-neoforge-0.5-sources.jar",
          "size": 27411,
          "sha512": "bea97f2b23c2e11620ef53b2a708257c3af57ce0b9caa59d370c4befa594c387a26fcf216d502f393c5b722276aee50c2cd671983ac4813a40362d40ef2cf701",
          "sha256": "baf47f6237b5bc10d8a7a6d5f438837e698a9026f2e96fadaaeeaa9ff5846eca",
          "sha1": "46a6a51c511d20731132e9f3c4ab66ea1aff1fb1",
          "md5": "400dd3f171663d2ad3a4c26d792d464c"
        }
      ]
    }
  ]
}
