{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.progames723.esll",
    "module": "esll",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "esll-1.1.jar",
          "url": "esll-1.1.jar",
          "size": 8811,
          "sha512": "294d7cbfd2eddd444b2543f32d99f33ce5c1470e16e2ff084ead8f129f4adfef12dc47788e1762cb40671a2e1c5fa78407aca85f990ee2d04e7d603be0553b0f",
          "sha256": "322f7ec6c1f4c88b4da174001136de52d028fd3f26cf02c21e6dfe0da24bf237",
          "sha1": "c76f1129a90e81890dea7ebd3b7e156182460350",
          "md5": "e13d36bfde05a0b2f918563b690de6ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "esll-1.1.jar",
          "url": "esll-1.1.jar",
          "size": 8811,
          "sha512": "294d7cbfd2eddd444b2543f32d99f33ce5c1470e16e2ff084ead8f129f4adfef12dc47788e1762cb40671a2e1c5fa78407aca85f990ee2d04e7d603be0553b0f",
          "sha256": "322f7ec6c1f4c88b4da174001136de52d028fd3f26cf02c21e6dfe0da24bf237",
          "sha1": "c76f1129a90e81890dea7ebd3b7e156182460350",
          "md5": "e13d36bfde05a0b2f918563b690de6ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "esll-1.1-sources.jar",
          "url": "esll-1.1-sources.jar",
          "size": 4746,
          "sha512": "c940f3df94e1a80059a0a791dfc2a453e938077f69d31452b35e552db835305abc4d03329572aee5a2498a78de0404825612186ed4c05f5a2cea7dfcda916a61",
          "sha256": "de8b7da3631e477bf09e5ef89098f1575be9cbd5eb104df8dc6c97b4a49c5bc2",
          "sha1": "c213486a76bb4b5d1896250d0f6e993c305ebdbd",
          "md5": "aa87b1d29b0153fed08c94e4c86bc6d1"
        }
      ]
    }
  ]
}
